### PR TITLE
add name mapping

### PR DESCRIPTION
**Pull request by Coding-Fun**
## Proposed changes
Add mapping for my slack name and github name. 
## Types of changes

What types of changes does your code introduce to BankrollHunter?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New script (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have tested the scripts with TradingView
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Haven't really picked up pine script yet but should be quick? :P

### CODE REVIEW

**Review by lisangzhou — APPROVED** [review]
LGTM 🚀

**Comment by lisangzhou** [comment]
> Haven't really picked up pine script yet but should be quick? :P

It's actually super shitty language. No casting, no filter .etc

**Review by donlingliang — APPROVED** [review]
🤣  you need two approvals for merging one line of readme.

**Comment by lisangzhou** [comment]
> 🤣 you need two approvals for merging one line of readme.

LOL we typed more comments than actual changes. 

but yeah not really able to create specific rules for documentation updates

**Pull request merged**
