### PR TITLE
Multi-Indicator in One

### PR DESCRIPTION
**Pull request by jchang274**
## Proposed changes

Describe your changes here to communicate to the maintainers why we should accept this pull request. If the changes fix an existing bug or issue that derived from any tradingview script, be sure to reference that script or the theory from LoneCapital.

## Types of changes

What types of changes does your code introduce to BankrollHunter?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New script (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have tested the scripts with TradingView
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jchang274** [comment]
Slack Name | Github Name | Skill Level
-- | -- | --
@ 20-物流-本科-jchang274| jchang274 | Starting

**Review by kentio — COMMENTED** [review]
太酷了，貌似又被tradingview屏蔽了。链接显示“Script Not Available”

**Comment by Coding-Fun** [comment]
`Multi-Indicator in ONE by jchang274` 两点建议
1. 可以把 `Multi-Indicator in ONE` 展开成具体的indicators，名字长点没关系。因为以后会有形形色色的multi-indicator combination，写具体的indicator会更清晰些
2. 可以把 `by jchang274` 去掉，从commit history上能看到你的贡献 :)

**Comment by Coding-Fun** [comment]
可以直接把代码放在.pine file里么 比如 https://github.com/bankrollhunter/tradingview-scripts/blob/develop/MA-Crossover/MA_Crossover_and_Px_Position.pine
这样code review会更方便 

zip file + password 相当于公开了 😛

**Comment by jchang274** [comment]
@kentio 现在只能用在日线，限制了乖离率的用法，我再想想土方法把周期问题解决了。

**Comment by jchang274** [comment]
@Coding-Fun  好的，下次直接放在.pine文件中。

**Review by jchang274 — COMMENTED** [review]
不同意

**Pull request closed without merging**
